src/drugformulary/views.py
"""
Flame Check
Views for the Drug Formulary API testing
"""

# Imports
import requests
from flask import (
    render_template, Blueprint, request, redirect, url_for
)

from .test_connection import test_connection
from .endpoint_totals import get_endpoint_total
from . import (
    medicationknowledge,
    lists,
)


# Blueprint
drugformulary_bp = Blueprint('drugformulary', __name__)


# Route - Landing Page
@drugformulary_bp.route('/drugformulary', methods=['GET', 'POST'])
def index():
    """Landing Page"""

    if request.method == 'POST':
        base_url = request.form.get('base_url')

        # Ensure the URL starts with https:// and ends with a slash
        if not base_url.startswith('https://'):
            base_url = f'https://{base_url}'
        if not base_url.endswith('/'):
            base_url = f'{base_url}/'

        api_endpoint = f"{base_url}fhirformulary/MedicationKnowledge"

        connection_result = test_connection(api_endpoint)

        if connection_result['success']:
            return redirect(url_for('drugformulary.test_endpoints',
                                    base_url=base_url))
        else:
            return render_template('drugformulary/index.html',
                                   title='Flame Check - Drug Formulary',
                                   connection_result=(
                                       connection_result['message']))

    return render_template('drugformulary/index.html',
                           title='Flame Check - Drug Formulary')


# Route - Test Endpoints
@drugformulary_bp.route('/drugformulary/test_endpoints',
                        methods=['GET'])
def test_endpoints():
    """Test Drug Formulary Endpoints"""
    # Get the base URL from the query string
    base_url = request.args.get('base_url')

    # Endpoints to test
    endpoints = [
        'List',
        'MedicationKnowledge',
    ]

    # Store results in a dictionary
    results = {endpoint: get_endpoint_total(
        base_url, endpoint) for endpoint in endpoints}

    return render_template('global/results_endpoints.html',
                           title='Flame Check - Test Endpoints',
                           base_url=base_url,
                           results=results)


# Route - Test MedicationKnowledge Search Parameters
@drugformulary_bp.route('/drugformulary/medicationknowledge_test',
                        methods=['GET'])
def medicationknowledge_test():
    """Test MedicationKnowledge Search Parameters"""
    base_url = request.args.get('base_url')
    try:
        first_entry = medicationknowledge.get_first_entry(base_url)
        results = {
            'status': medicationknowledge.get_status(first_entry),
            'code': medicationknowledge.get_code(first_entry),
            'drug-name': medicationknowledge.get_drug_name(first_entry),
            'doseform': medicationknowledge.get_doseform(first_entry),
            '_id': medicationknowledge.get_id(first_entry),
            '_lastUpdated': medicationknowledge.get_last_updated(first_entry)
        }
    except requests.exceptions.RequestException as e:
        results = {'error': str(e)}

    return render_template('global/results_search_parameters.html',
                           title='Flame Check - Test medicationknowledge',
                           results=results,
                           search_parameter_comments=(
                               medicationknowledge.search_parameter_comments))


# Route - Test MedicationKnowledge Required Data Elements
@drugformulary_bp.route('/drugformulary/medicationknowledge_required',
                        methods=['GET'])
def medicationknowledge_required():
    """
    Test MedicationKnowledge Required Data Elements
    with 10 Random Entries
    """
    base_url = request.args.get('base_url')
    try:
        entries = medicationknowledge.get_entries(base_url)
        results = [
            {
                '_id': medicationknowledge.get_id(entry),
                '_lastUpdated': medicationknowledge.get_last_updated(entry),
                'code': medicationknowledge.get_code(entry),
                'drug-name': medicationknowledge.get_drug_name(entry),
                'status': medicationknowledge.get_status(entry),
                'doseform': medicationknowledge.get_doseform(entry)
            }
            for entry in entries
        ]
    except requests.exceptions.RequestException as e:
        results = {'error': str(e)}

    return render_template('global/results_required.html',
                           title='Flame Check - Required Data Elements',
                           results=results,)


# Route - Test List Search Parameters
@drugformulary_bp.route('/drugformulary/list_test', methods=['GET'])
def list_test():
    """Test List Search Parameters"""
    base_url = request.args.get('base_url')
    try:
        first_entry = lists.get_first_entry(base_url)
        results = {
            'identifier': lists.get_identifier(first_entry),
            'status': lists.get_status(first_entry),
            '_id': lists.get_id(first_entry),
            '_lastUpdated': lists.get_last_updated(first_entry)
        }
    except requests.exceptions.RequestException as e:
        results = {'error': str(e)}

    return render_template('global/results_search_parameters.html',
                           title='Flame Check - Test List',
                           results=results,
                           search_parameter_comments=(
                               lists.search_parameter_comments))


# Route - Test List Required Data Elements
@drugformulary_bp.route('/drugformulary/list_required', methods=['GET'])
def list_required():
    """Test List Required Data Elements with 10 Random Entries"""
    base_url = request.args.get('base_url')
    try:
        entries = lists.get_entries(base_url)
        results = [{'_id': lists.get_id(entry),
                    '_lastUpdated': lists.get_last_updated(entry),
                    'identifier': lists.get_identifier(entry),
                    'status': lists.get_status(entry)} for entry in entries]
    except requests.exceptions.RequestException as e:
        results = {'error': str(e)}

    return render_template('global/results_required.html',
                           title='Flame Check - Required Data Elements',
                           results=results,)

src/providerdirectory/views.py
"""
Flame Check
Views for the Provider Directory API testing
"""

# Imports
import requests
from flask import (
    render_template, Blueprint, request, redirect, url_for
)

from .test_connection import test_connection
from .endpoint_totals import get_endpoint_total
from .ten_random_entries import get_entries
from . import (
    healthcareservice,
    practitioner,
    practitionerrole,
    insuranceplan,
    location,
    organization,
    organizationaffiliation as oa,
)

# Blueprint
provdir_bp = Blueprint('provdir', __name__)


# Route - Landing Page
@provdir_bp.route('/provdir', methods=['GET', 'POST'])
def index():
    """Landing Page"""

    if request.method == 'POST':
        base_url = request.form.get('base_url')

        # Ensure the URL starts with https:// and ends with a slash
        if not base_url.startswith('https://'):
            base_url = f'https://{base_url}'
        if not base_url.endswith('/'):
            base_url = f'{base_url}/'

        api_endpoint = f"{base_url}fhirprovdir/Practitioner"

        connection_result = test_connection(api_endpoint)

        if connection_result['success']:
            return redirect(url_for('provdir.test_endpoints',
                                    base_url=base_url))
        else:
            return render_template('provdir/index.html',
                                   title='Flame Check - Provider Directory',
                                   connection_result=(
                                       connection_result['message']))

    return render_template('provdir/index.html',
                           title='Flame Check - Provider Directory')


# Route - Test Endpoints
@provdir_bp.route('/test_endpoints', methods=['GET'])
def test_endpoints():
    """Test Provider Directory Endpoints"""
    # Get the base URL from the query string
    base_url = request.args.get('base_url')

    # Endpoints to test
    endpoints = [
        'Endpoint',
        'HealthcareService',
        'InsurancePlan',
        'Location',
        'Organization',
        'OrganizationAffiliation',
        'Practitioner',
        'PractitionerRole',
    ]

    # Store results in a dictionary
    results = {endpoint: get_endpoint_total(
        base_url, endpoint) for endpoint in endpoints}

    return render_template('global/results_endpoints.html',
                           title='Flame Check - Test Endpoints',
                           base_url=base_url,
                           results=results)


# Route - Test HealthcareService Search Paramters
@provdir_bp.route('/healthcareservice_test', methods=['GET'])
def healthcareservice_test():
    """Test HealthcareService Search Parameters"""
    # Get the base URL from the query string
    base_url = request.args.get('base_url')

    # Get the first entry from the endpoint
    try:
        first_entry = healthcareservice.get_first_entry(base_url)
    except requests.exceptions.RequestException as e:
        results = {'error': str(e)}
        return render_template('global/results_search_parameters.html',
                               title='Flame Check - Test HealthcareService',
                               results=results,
                               search_parameter_comments=(
                                   healthcareservice.search_parameter_comments
                               ))

    # Get the various fields from the first entry
    results = {
        'location': healthcareservice.get_location(first_entry),
        'coverage-area': healthcareservice.get_coverage_area(first_entry),
        'organization': healthcareservice.get_organization(first_entry),
        'endpoint': healthcareservice.get_endpoint(first_entry),
        'name': healthcareservice.get_name(first_entry),
        'service-category': healthcareservice.get_service_category(
            first_entry),
        'service-type': healthcareservice.get_service_type(first_entry),
        'specialty': healthcareservice.get_specialty(first_entry),
        '_id': healthcareservice.get_id(first_entry),
        '_lastUpdated': healthcareservice.get_last_updated(first_entry)
    }

    return render_template('global/results_search_parameters.html',
                           title='Flame Check - Test HealthcareService',
                           results=results,
                           search_parameter_comments=(
                               healthcareservice.search_parameter_comments))


# Route - Test HealthcareService Required Data Elements
@provdir_bp.route('/healthcareservice_required', methods=['GET'])
def healthcareservice_required():
    """
    Test HealthcareService Required Data Elements with 10 Random Entries
    """
    base_url = request.args.get('base_url')
    try:
        entries = get_entries(base_url, 'HealthcareService')
        results = [
            {
                '_id': healthcareservice.get_id(entry),
                '_lastUpdated': healthcareservice.get_last_updated(entry),
                'location': healthcareservice.get_location(entry),
                'organization': healthcareservice.get_organization(entry),
                'name': healthcareservice.get_name(entry),
                'service-category': healthcareservice.get_service_category(
                    entry),
                'service-type': healthcareservice.get_service_type(entry),
                'specialty': healthcareservice.get_specialty(entry),
            } for entry in entries
        ]
    except requests.exceptions.RequestException as e:
        results = {'error': str(e)}

    return render_template('global/results_required.html',
                           title='Flame Check - Required Data Elements',
                           results=results,)


# Route - Test InsurancePlan Search Paramters
@provdir_bp.route('/insuranceplan_test', methods=['GET'])
def insuranceplan_test():
    """Test InsuranceType Search Parameters"""
    # Get the base URL from the query string
    base_url = request.args.get('base_url')

    # Get the first entry from the endpoint
    try:
        first_entry = insuranceplan.get_first_entry(base_url)
    except requests.exceptions.RequestException as e:
        results = {'error': str(e)}
        return render_template('global/results_search_parameters.html',
                               title='Flame Check - Test InsurancePlan',
                               results=results)

    # Get the various fields from the first entry
    results = {
        'administered-by': insuranceplan.get_administer_by(first_entry),
        'owned-by': insuranceplan.get_owned_by(first_entry),
        'coverage-area': insuranceplan.get_coverage_area(first_entry),
        'name': insuranceplan.get_name(first_entry),
        'plan-type': insuranceplan.get_plan_type(first_entry),
        'identifier': insuranceplan.get_identifier(first_entry),
        '_id': insuranceplan.get_id(first_entry),
        '_lastUpdated': insuranceplan.get_last_updated(first_entry),
        'type': insuranceplan.get_type(first_entry),
    }

    return render_template('global/results_search_parameters.html',
                           title='Flame Check - Test InsurancePlan',
                           results=results,
                           search_parameter_comments=(
                               insuranceplan.search_parameter_comments))


# Route - Test InsurancePlan Required Data Elements
@provdir_bp.route('/insuranceplan_required', methods=['GET'])
def insuranceplan_required():
    """
    Test InsurancePlan Required Data Elements with 10 Random Entries
    """
    base_url = request.args.get('base_url')
    try:
        entries = get_entries(base_url, 'InsurancePlan')
        results = [
            {
                '_id': insuranceplan.get_id(entry),
                '_lastUpdated': insuranceplan.get_last_updated(entry),
                'administered-by': insuranceplan.get_administer_by(entry),
                'owned-by': insuranceplan.get_owned_by(entry),
                'coverage-area': insuranceplan.get_coverage_area(entry),
                'name': insuranceplan.get_name(entry),
                'plan-type': insuranceplan.get_plan_type(entry),
                'identifier': insuranceplan.get_identifier(entry),
            } for entry in entries
        ]
    except requests.exceptions.RequestException as e:
        results = {'error': str(e)}

    return render_template('global/results_required.html',
                           title='Flame Check - Required Data Elements',
                           results=results,)


# Route - Test Location Search Paramters
@provdir_bp.route('/location_test', methods=['GET'])
def location_test():
    """Test Location Search Parameters"""
    # Get the base URL from the query string
    base_url = request.args.get('base_url')

    # Get the first entry from the endpoint
    try:
        first_entry = location.get_first_entry(base_url)
    except requests.exceptions.RequestException as e:
        results = {'error': str(e)}
        return render_template('global/results_search_parameters.html',
                               title='Flame Check - Test Location',
                               results=results)

    # Get the various fields from the first entry
    results = {
        'partof': location.get_part_of(first_entry),
        'organization': location.get_organization(first_entry),
        'endpoint': location.get_endpoint(first_entry),
        'address-city': location.get_address_city(first_entry),
        'address-state': location.get_address_state(first_entry),
        'address-postalcode': location.get_address_postalcode(first_entry),
        'address': location.get_address(first_entry),
        'type': location.get_type(first_entry),
        '_id': location.get_id(first_entry),
        '_lastUpdated': location.get_last_updated(first_entry)
    }

    return render_template('global/results_search_parameters.html',
                           title='Flame Check - Test Location',

src/templates/global/results_endpoints.html
{% extends 'base.html' %} {% block content %}
<h1>Test Results</h1>

<!-- Placeholder -->
<div id="placeholder">
  <div class="d-flex justify-content-center">
    <div
      class="spinner-border text-primary"
      style="width: 10rem; height: 10rem"
      role="status"
    >
      <span class="visually-hidden">Loading...</span>
    </div>
  </div>
</div>

<!-- Actual table (hidden by default) -->
<table id="actualTable" class="table" style="display: none">
  <thead>
    <tr>
      <th>Endpoint</th>
      <th>Total Entries</th>
      <th>Test Endpoint</th>
    </tr>
  </thead>
  <tbody>
    {% for endpoint, total_entries in results.items() %}
    <tr>
      <td>{{ endpoint }}</td>
      <td>{{ total_entries }}</td>
      <td>
        <a
          class="btn btn-primary"
          {% if endpoint == 'MedicationKnowledge' %}
            href="{{ url_for('drugformulary.medicationknowledge_required', base_url=base_url) }}"
          {% elif endpoint == 'List' %}
            href="{{ url_for('drugformulary.list_required', base_url=base_url) }}"
          {% elif endpoint == 'HealthcareService' %}
            href="{{ url_for('provdir.healthcareservice_required', base_url=base_url) }}"
          {% elif endpoint == 'InsurancePlan' %}
            href="{{ url_for('provdir.insuranceplan_required', base_url=base_url) }}"
          {% elif endpoint == 'Location' %}
            href="{{ url_for('provdir.location_required', base_url=base_url) }}"
          {% elif endpoint == 'Organization' %}
            href="{{ url_for('provdir.organization_required', base_url=base_url) }}"
          {% elif endpoint == 'OrganizationAffiliation' %}
            href="{{ url_for('provdir.organizationaffiliation_required', base_url=base_url) }}"
          {% elif endpoint == 'Practitioner' %}
            href="{{ url_for('provdir.practitioner_required', base_url=base_url) }}"
          {% elif endpoint == 'PractitionerRole' %}
            href="{{ url_for('provdir.practitionerrole_required', base_url=base_url) }}"
          {% endif %}
          >Test Required Data</a
        >
        <a
          class="btn btn-success"
          {% if endpoint == 'Practitioner' %}
            href="{{ url_for('provdir.practitioner_test', base_url=base_url) }}"
          {% elif endpoint == 'Organization' %}
            href="{{ url_for('provdir.organization_test', base_url=base_url) }}"
          {% elif endpoint == 'OrganizationAffiliation' %}
            href="{{ url_for('provdir.organizationaffiliation_test', base_url=base_url) }}"
          {% elif endpoint == 'Location' %}
            href="{{ url_for('provdir.location_test', base_url=base_url) }}"
          {% elif endpoint == 'HealthcareService' %}
            href="{{ url_for('provdir.healthcareservice_test', base_url=base_url) }}"
          {% elif endpoint == 'Endpoint' %}
            href="#"
          {% elif endpoint == 'PractitionerRole' %}
            href="{{ url_for('provdir.practitionerrole_test', base_url=base_url) }}"
          {% elif endpoint == 'InsurancePlan' %}
            href="{{ url_for('provdir.insuranceplan_test', base_url=base_url) }}"
          {% elif endpoint == 'List' %}
            href="{{ url_for('drugformulary.list_test', base_url=base_url) }}"
          {% elif endpoint == 'MedicationKnowledge' %}
            href="{{ url_for('drugformulary.medicationknowledge_test', base_url=base_url) }}"
          {% endif %}
          >Test Search Parameters</a
        >
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<script>
  window.addEventListener("load", function () {
    document.getElementById("placeholder").style.display = "none";
    document.getElementById("actualTable").style.display = "table";
  });
</script>
{% endblock content %}

src/templates/global/results_required.html
{% extends 'base.html' %} {% block content %}
<h1>Test Results</h1>

<!-- Placeholder -->
<div id="placeholder">
  <div class="d-flex justify-content-center">
    <div
      class="spinner-border text-primary"
      style="width: 10rem; height: 10rem"
      role="status"
    >
      <span class="visually-hidden">Loading...</span>
    </div>
  </div>
</div>

<!-- Required Results Table -->
<table class="table table-striped" id="actualTable" style="display: none">
  <thead>
    <tr>
      <!-- Loop through the entries and find the keys in the JSON. Each key will be the table header -->
      {% for key in results[0] %}
      <th scope="col">{{ key }}</th>
      {% endfor %}
    </tr>
  </thead>
  <tbody>
    <!-- Loop through the entries and find the values in the JSON. Each value will be the table data -->
    {% for entry in results %}
    <tr>
      {% for key, value in entry.items() %}
      <td>{{ value }}</td>
      {% endfor %}
    </tr>
    {% endfor %}
  </tbody>
</table>

<script>
  window.addEventListener("load", function () {
    document.getElementById("placeholder").style.display = "none";
    document.getElementById("actualTable").style.display = "table";
  });
</script>
{% endblock content %}

src/templates/global/results_search_parameters.html
{% extends 'base.html' %} {% block content %}
<h1>Test Results</h1>

<!-- Placeholder -->
<div id="placeholder">
  <div class="d-flex justify-content-center">
    <div
      class="spinner-border text-primary"
      style="width: 10rem; height: 10rem"
      role="status"
    >
      <span class="visually-hidden">Loading...</span>
    </div>
  </div>
</div>

<!-- Search Paramter Result Table -->
<table class="table" id="actualTable" style="display: none">
  <thead>
    <tr>
      <th>Search Parameter</th>
      <th>Result</th>
      <th>ODS Data Map/Comments</th>
    </tr>
  </thead>
  <tbody>
    {% for search_parameter, result in results.items() %}
    <tr>
      <td>{{ search_parameter }}</td>
      <td>{{ result }}</td>
      <td>
        {% if search_parameter in search_parameter_comments %} {{
        search_parameter_comments[search_parameter] }} {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<script>
  window.addEventListener("load", function () {
    document.getElementById("placeholder").style.display = "none";
    document.getElementById("actualTable").style.display = "table";
  });
</script>
{% endblock content %}